#Properties  
# Http Client Configutation
tomcat:
  ajp:
    protocol: "AJP/1.3"
    port: 6107
    enabled: true

http:
  client:
    max:
      total-connection: 20
      per-route: 5

# Service Token Define  
token:
  expire-sec:
    access: 2419200
    refresh: 315576000
  validate:
    addPath:
      - "/coupon/*"
      
spring:
  profiles: test 